server:
  port: 8080
  servlet:
    context-path: "/api"

spring:
  application:
    name: "eCommerce"
  datasource:
    url: "jdbc:mysql://localhost:3306/ecommerce-dev?createDatabaseIfNotExist=true"
    username: root
    password: 26072000Ha.
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: true

logging:
  level:
    org:
      springframework:
        security: debug

jwt:
  signerKey: "N63ovOSTkXu/FKEHw3O6zewRhBW7IXuFYJUjDIBezE6uBhrNYw/dVtCmGPz5rexb"
  invalid-duration: 3600 # in seconds
  refreshable-duration: 36000

springdoc:
  swagger-ui:
    enable: true
    operationsSorter: alpha  #For sorting tags alphabetically
    tagsSorter: alpha
    doc-expansion: false

  api-docs:
    path: /api-docs